// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYIT73Foz9GhTs_aVH88WRAeWfHezdxQ',
    appId: '1:590372011957:web:f41d601ffce2f8deac63fc',
    messagingSenderId: '590372011957',
    projectId: 'pixelpulse-auth',
    authDomain: 'pixelpulse-auth.firebaseapp.com',
    storageBucket: 'pixelpulse-auth.appspot.com',
    measurementId: 'G-C8Q2P1CDPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3FqRgPAIIDsF44L-RU578-_28LLcBhgI',
    appId: '1:590372011957:android:3d511daf7703be2eac63fc',
    messagingSenderId: '590372011957',
    projectId: 'pixelpulse-auth',
    storageBucket: 'pixelpulse-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe7CAuo-DjqCX5k7_h-jlgr7Vc1a0y4Us',
    appId: '1:590372011957:ios:6dc5341cd5874831ac63fc',
    messagingSenderId: '590372011957',
    projectId: 'pixelpulse-auth',
    storageBucket: 'pixelpulse-auth.appspot.com',
    iosBundleId: 'com.example.pixelpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe7CAuo-DjqCX5k7_h-jlgr7Vc1a0y4Us',
    appId: '1:590372011957:ios:6dc5341cd5874831ac63fc',
    messagingSenderId: '590372011957',
    projectId: 'pixelpulse-auth',
    storageBucket: 'pixelpulse-auth.appspot.com',
    iosBundleId: 'com.example.pixelpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCYIT73Foz9GhTs_aVH88WRAeWfHezdxQ',
    appId: '1:590372011957:web:75f49a5d32545675ac63fc',
    messagingSenderId: '590372011957',
    projectId: 'pixelpulse-auth',
    authDomain: 'pixelpulse-auth.firebaseapp.com',
    storageBucket: 'pixelpulse-auth.appspot.com',
    measurementId: 'G-RH4SXTYY54',
  );
}
